/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LayoutRouteImport } from './routes/_layout'
import { Route as IndexRouteImport } from './routes/index'
import { Route as LayoutTransactionsRouteImport } from './routes/_layout.transactions'
import { Route as LayoutMempoolRouteImport } from './routes/_layout.mempool'
import { Route as LayoutBlocksRouteImport } from './routes/_layout.blocks'
import { Route as LayoutAccountsRouteImport } from './routes/_layout.accounts'
import { Route as LayoutTxHashRouteImport } from './routes/_layout.tx.$hash'
import { Route as LayoutTokenAddressRouteImport } from './routes/_layout.token.$address'
import { Route as LayoutBlockHashRouteImport } from './routes/_layout.block.$hash'
import { Route as LayoutAccountAddressRouteImport } from './routes/_layout.account.$address'

const LayoutRoute = LayoutRouteImport.update({
  id: '/_layout',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const LayoutTransactionsRoute = LayoutTransactionsRouteImport.update({
  id: '/transactions',
  path: '/transactions',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutMempoolRoute = LayoutMempoolRouteImport.update({
  id: '/mempool',
  path: '/mempool',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutBlocksRoute = LayoutBlocksRouteImport.update({
  id: '/blocks',
  path: '/blocks',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutAccountsRoute = LayoutAccountsRouteImport.update({
  id: '/accounts',
  path: '/accounts',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutTxHashRoute = LayoutTxHashRouteImport.update({
  id: '/tx/$hash',
  path: '/tx/$hash',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutTokenAddressRoute = LayoutTokenAddressRouteImport.update({
  id: '/token/$address',
  path: '/token/$address',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutBlockHashRoute = LayoutBlockHashRouteImport.update({
  id: '/block/$hash',
  path: '/block/$hash',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutAccountAddressRoute = LayoutAccountAddressRouteImport.update({
  id: '/account/$address',
  path: '/account/$address',
  getParentRoute: () => LayoutRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/accounts': typeof LayoutAccountsRoute
  '/blocks': typeof LayoutBlocksRoute
  '/mempool': typeof LayoutMempoolRoute
  '/transactions': typeof LayoutTransactionsRoute
  '/account/$address': typeof LayoutAccountAddressRoute
  '/block/$hash': typeof LayoutBlockHashRoute
  '/token/$address': typeof LayoutTokenAddressRoute
  '/tx/$hash': typeof LayoutTxHashRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/accounts': typeof LayoutAccountsRoute
  '/blocks': typeof LayoutBlocksRoute
  '/mempool': typeof LayoutMempoolRoute
  '/transactions': typeof LayoutTransactionsRoute
  '/account/$address': typeof LayoutAccountAddressRoute
  '/block/$hash': typeof LayoutBlockHashRoute
  '/token/$address': typeof LayoutTokenAddressRoute
  '/tx/$hash': typeof LayoutTxHashRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_layout': typeof LayoutRouteWithChildren
  '/_layout/accounts': typeof LayoutAccountsRoute
  '/_layout/blocks': typeof LayoutBlocksRoute
  '/_layout/mempool': typeof LayoutMempoolRoute
  '/_layout/transactions': typeof LayoutTransactionsRoute
  '/_layout/account/$address': typeof LayoutAccountAddressRoute
  '/_layout/block/$hash': typeof LayoutBlockHashRoute
  '/_layout/token/$address': typeof LayoutTokenAddressRoute
  '/_layout/tx/$hash': typeof LayoutTxHashRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/accounts'
    | '/blocks'
    | '/mempool'
    | '/transactions'
    | '/account/$address'
    | '/block/$hash'
    | '/token/$address'
    | '/tx/$hash'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/accounts'
    | '/blocks'
    | '/mempool'
    | '/transactions'
    | '/account/$address'
    | '/block/$hash'
    | '/token/$address'
    | '/tx/$hash'
  id:
    | '__root__'
    | '/'
    | '/_layout'
    | '/_layout/accounts'
    | '/_layout/blocks'
    | '/_layout/mempool'
    | '/_layout/transactions'
    | '/_layout/account/$address'
    | '/_layout/block/$hash'
    | '/_layout/token/$address'
    | '/_layout/tx/$hash'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LayoutRoute: typeof LayoutRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_layout': {
      id: '/_layout'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof LayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_layout/transactions': {
      id: '/_layout/transactions'
      path: '/transactions'
      fullPath: '/transactions'
      preLoaderRoute: typeof LayoutTransactionsRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/mempool': {
      id: '/_layout/mempool'
      path: '/mempool'
      fullPath: '/mempool'
      preLoaderRoute: typeof LayoutMempoolRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/blocks': {
      id: '/_layout/blocks'
      path: '/blocks'
      fullPath: '/blocks'
      preLoaderRoute: typeof LayoutBlocksRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/accounts': {
      id: '/_layout/accounts'
      path: '/accounts'
      fullPath: '/accounts'
      preLoaderRoute: typeof LayoutAccountsRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/tx/$hash': {
      id: '/_layout/tx/$hash'
      path: '/tx/$hash'
      fullPath: '/tx/$hash'
      preLoaderRoute: typeof LayoutTxHashRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/token/$address': {
      id: '/_layout/token/$address'
      path: '/token/$address'
      fullPath: '/token/$address'
      preLoaderRoute: typeof LayoutTokenAddressRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/block/$hash': {
      id: '/_layout/block/$hash'
      path: '/block/$hash'
      fullPath: '/block/$hash'
      preLoaderRoute: typeof LayoutBlockHashRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/account/$address': {
      id: '/_layout/account/$address'
      path: '/account/$address'
      fullPath: '/account/$address'
      preLoaderRoute: typeof LayoutAccountAddressRouteImport
      parentRoute: typeof LayoutRoute
    }
  }
}

interface LayoutRouteChildren {
  LayoutAccountsRoute: typeof LayoutAccountsRoute
  LayoutBlocksRoute: typeof LayoutBlocksRoute
  LayoutMempoolRoute: typeof LayoutMempoolRoute
  LayoutTransactionsRoute: typeof LayoutTransactionsRoute
  LayoutAccountAddressRoute: typeof LayoutAccountAddressRoute
  LayoutBlockHashRoute: typeof LayoutBlockHashRoute
  LayoutTokenAddressRoute: typeof LayoutTokenAddressRoute
  LayoutTxHashRoute: typeof LayoutTxHashRoute
}

const LayoutRouteChildren: LayoutRouteChildren = {
  LayoutAccountsRoute: LayoutAccountsRoute,
  LayoutBlocksRoute: LayoutBlocksRoute,
  LayoutMempoolRoute: LayoutMempoolRoute,
  LayoutTransactionsRoute: LayoutTransactionsRoute,
  LayoutAccountAddressRoute: LayoutAccountAddressRoute,
  LayoutBlockHashRoute: LayoutBlockHashRoute,
  LayoutTokenAddressRoute: LayoutTokenAddressRoute,
  LayoutTxHashRoute: LayoutTxHashRoute,
}

const LayoutRouteWithChildren =
  LayoutRoute._addFileChildren(LayoutRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LayoutRoute: LayoutRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
